language: node_js
sudo: false
node_js:
- '6'
- '8'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - secure: f2bXA8WPOChqOalMBU8uJmyO0i3Q32xlunEOwpWMVyq+7aQ8KqFYHhzaxIml6mbSbPFlG8KB8o/LraQ84rTiVzxUHnyIqf6UkkTdPBaFSoShNJ7ddEITRxuliWotSqHZANE64PbD++z20GOyUfFVl3CuRwc/AXvVqTGXpPGup/QruvVCudYqz2x1wujjX6+B2RxpVb/tQGw+C9U2Rdz+hJbATFPuzeoQGcyWv3kAltU17RCr/CP/EkNAXdNIaLQFusSY8um1en1tJrGO+XS32jLogknfbAp5JbFT/o6gz0h0E1JQmtSAckqVuOVm8Z0u8APjV5Ph8feWJyXTjk9YNcDnuWLhfpr19MJcYOYzGzWGb32/W/M08ELE75HrDDiqd5VlAPLeIQ51zyvyfF1WrDIH/Ok62O+Oc6Rr/PqlJmTOkKzUq+5IERbo1yWCneDqOdNM3m73wsrz8xlsLHz1Aytnizh5Cy0qBnNl09IXuwdZTwIylyE8SjqY7OZ4pt0Hm8RjlYUQeis8M04yXh2C84qjeK22mWLWeYGYR/DX61MAEqI5dkmO/LVjmLRHPlFQdfEnME8wMjlY2O0JhEN45UCINqT9VlMzzft0YOpvtPPbPrLStKOOtyO63yd3X71uUJgb4lEAV14v9iDu81xCseIp1M4ONyxxAriAE62CSl0=
  - secure: a5bRXmVmtk1AkIoN+QFAfoJe4IKdt75vu7oTWJJ4oKvsb2U1Mm32qTMxDPqCJKHXnhmD7kXphEeBiRMNbsdL5hXheQFPX9V9w4T1sl0OjGTlPe3Z/PX6KlmjGc85yt/fovvywrp/OOnO0nFwTa4KQOjr4ctxlOhtbBkXKsAA+rbyCTDpGLEvgAxrHkx6tu1aks9t4TqOoqGfrjyRXSgxcEnj1LA871q6YdaT31cll42DmKOe1TZEuzthd3jcLEKeav1nhYMEigPN+0SLlgKlz6JKn4oQKF4rQzNnC0c4ZFeEp8t0nfg4Vx596DSV56MxI/KH7PHYryyknBcS9tzFuWc+Vtwhpq8a3pVMhsxXOXvs+BoW1xeSbco8s8zAYpBdTRU8GsvQtYkltMPapCThuDVxJkeyyYPIWSsl94MkpKV0fm0WSifN3IB35OQCiFb9PUPfDl8AC4fF0a7dM5flmhlH7EExdL94DWzFiurV9DKzMsHnftffS6O+UQwufJC3Z5IeJBjqdHqZUbCaAGTOQH2rbqqQIixZVIS07dw42o++vQ3E89hGi7p06cQcrI2xvzPMNhMzZANTArw5vk/5FMdLsGncOPDZZ11a6mulArDmQKNu2oCyfIuwpehvRhRQ9uQ3z01O0L0sOpFicIXAhhuDj3YOYyoVc+0QDV19+rM=
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  skip_cleanup: true
  api_key:
    secure: j75Ywog9fLXszv6yAqtm9uHAheCF3khte7+NinmV3CKyoM0LBrfqX3d3UeLjKEhGKMNDrtOjbi5FkfHoY7dg7FTT905hLA6losEmG6cJtPiFdk/p7cK/Po4lIxUsjS9YWiRK0UuNhzWhuU9oQtcc8BBZRlv1yyidgxMYtLjR84SaMV5Vx8b4smlsrprUObSiuThP41Vps0fxy8IpJ6S2VK9+3mjmqy19C+slOwN4KjabENOThIWW28bCsnPj9djihqPHLyH3B3jurOmewaJWCXYBz9LSRVKI4AzcRW22RjlBV1gyInpilXedV2dT9yc+sU0pT+LI6NXLrEThVuximRu/F1HGHkay4U2tWu+f83Y/fTOlWDdFor4Nnjea67JA8+6RnX+FNeNJs7jhUN6WPf8eIEhXpSrUCSeGxBjkvIGUw2T/hoxSnvHHFVKaiYhhgF3pkjSziYg5I2/iOvJeAD6HV5Wepv5INjdpptdPFywrW7vm9cE9oPHixGSk5vd5Nk4+JG5qulO+GpxvSguvzWj7IvyCDoX8Mzk2fRIPtDebftKEzekwD7ARW/sc7JnatiOC3rjtfjYTr3LSku7zsnAnJQnv6X9HGS+3WOy3DtCmEMqLjAfDplcCC0eSgKZ+ERsgxj1CYwUGpdKyjfGgixmQS3d2emnVDFNj6236JAI=
  on:
    tags: true
    repo: taskcluster/azure-blob-storage
