language: node_js
sudo: false
node_js:
- '8'
- '10'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - secure: D5qEl7EYMaaS1bTxBAxVwM+f7YmtOHDdHzf3FhMGxfq9V5khiDw7yXEdwayCHWV1uDL4o79XuOJg6axOT5yA6nJNXOWFf1Gdu9nMwl9i8g+zIndWKr1ITg7/RaDerHCQB2cdnvVZKswP1GdhLyzC3KKeGFlPM+Q/jLa/F0P0gnoH8eFFT4ba7xGgBRt5um0WYRYeaHEwptT4IH5W6kSGE7olQOe78+D51bohxZiTVGsCJAj5lAuQyQpxZyvQmtuV0iDiwxSHGVFDY4tiOsUTRyNgEwNreXj8Mh0etvVrdmNaW/mnH6gSR0kz79ISeg8xID3ZzUqzTJ0YT0jBeG/cdpRxd6VfJDI5X7ibcazwYL8BznXj8hEsRkdbPehd3EnvAvUQzl3+pdL0JUM6RnZ1LlxsGtoE7I4Vg/9s7afuiv9bzsSk8mPqpa+jV87pVxvxSLAKCW2kbece/7fuVG5nDbQtJTggLmIe5DkhBXrUqi/bBVlWNfwhaPWjngdKAxO02MZ8A+YPw1MwpOEBLVkprokzByXOCPHudzkeFIHk+FeM20THCJhMqS65Otw2hlrQKd6y0TQIop9BxMJvwAKEBNbDNbYCKgCWqwsE7XxZ4qbYZxwH1frqiw15UvGnGQYGBqm7j3G5I+l4gCOE9zj0bcx6UVPx1YkzpOkVyungsn8=
  - secure: LssoMUTO3ZTTb/X33scN+iTYesfLAx+eoKwu/CLSEvdcR7p0x9k3UWDnO1ovs4pGOR3PoXOi+N/frs9+TSshJgLiXvQiLvUYHAWWur1V/PBuoihmYEPxFxGLaJCUDPPHqjrDAYpwOMWsRaD/GcTJbd2o+ik4UBSNLk2dPKi/gGy0Oy1USt6wKtFk2GLvgWTQvhjn972x1Q+yC9LMUgU4C9I7mrb9tnd7MBbJmA9dtckGrBHfReDOI3OcC2VsSmztjUQ/ozUbaMOuNeXtUebBA3zJm2Ifo+sC2qctOPa1TXB9rkRQE//PkYlscHz7BZ+ggSMpPDDq9uKuzfPHdRAvoWFpqVyrrpHRDkbGqob/fqvxqPVcz0irrEJIYNBBXiV86jsm7u5p3/y1LITbTRRkJYhXs8Bs3bppk3Uny0oKaO8UOUQQD8dwPayMH8uUK7XEDvMslx7UGgHHTe5xt9s8RiN4gdjBbyStukjks6vtgo2l+bcKc4aO/A4z4TochtSwoALChzmf5ADv1kxiQzlX67aa6NTq15in298DHnAMLqioKlp3TzZF9H4351y9Ai4NUcIjkQPpfzHUoMNdGSzC/nl87RLOj8fRVN+gXF6Nq6xuhGiLVaPq0lfvw6NovMHuuaEMTkL//JuEB2kWKpN1zEvWcNkVgCHF4iWQtjpB0Oo=
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  skip_cleanup: true
  api_key:
    secure: j75Ywog9fLXszv6yAqtm9uHAheCF3khte7+NinmV3CKyoM0LBrfqX3d3UeLjKEhGKMNDrtOjbi5FkfHoY7dg7FTT905hLA6losEmG6cJtPiFdk/p7cK/Po4lIxUsjS9YWiRK0UuNhzWhuU9oQtcc8BBZRlv1yyidgxMYtLjR84SaMV5Vx8b4smlsrprUObSiuThP41Vps0fxy8IpJ6S2VK9+3mjmqy19C+slOwN4KjabENOThIWW28bCsnPj9djihqPHLyH3B3jurOmewaJWCXYBz9LSRVKI4AzcRW22RjlBV1gyInpilXedV2dT9yc+sU0pT+LI6NXLrEThVuximRu/F1HGHkay4U2tWu+f83Y/fTOlWDdFor4Nnjea67JA8+6RnX+FNeNJs7jhUN6WPf8eIEhXpSrUCSeGxBjkvIGUw2T/hoxSnvHHFVKaiYhhgF3pkjSziYg5I2/iOvJeAD6HV5Wepv5INjdpptdPFywrW7vm9cE9oPHixGSk5vd5Nk4+JG5qulO+GpxvSguvzWj7IvyCDoX8Mzk2fRIPtDebftKEzekwD7ARW/sc7JnatiOC3rjtfjYTr3LSku7zsnAnJQnv6X9HGS+3WOy3DtCmEMqLjAfDplcCC0eSgKZ+ERsgxj1CYwUGpdKyjfGgixmQS3d2emnVDFNj6236JAI=
  on:
    tags: true
    repo: taskcluster/azure-blob-storage
